### ISSUE TITLE
[netzob] AttributeError: 'module' object has no attribute 'ARP'

### ISSUE THREAD

**Issue by leviathan2701** [netzob/netzob#116]
Hi,

When I want to import a pcap, the program output this errror:

```
Traceback (most recent call last):
  File "reverse_protocol.py", line 311, in <module>
    main()
  File "reverse_protocol.py", line 192, in main
    importLayer=4).values()
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Common/Utils/Decorators.py", line 188, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Import/PCAPImporter/PCAPImporter.py", line 515, in readFile
    nbPackets, mergePacketsInFlow)
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Common/Utils/Decorators.py", line 188, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Import/PCAPImporter/PCAPImporter.py", line 485, in readFiles
    return importer.readMessages(filePathList,bpfFilter, importLayer, nbPackets, mergePacketsInFlow)
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Common/Utils/Decorators.py", line 188, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Import/PCAPImporter/PCAPImporter.py", line 442, in readMessages
    self.__readMessagesFromFile(filePath, bpfFilter, nbPackets)
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Common/Utils/Decorators.py", line 188, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Import/PCAPImporter/PCAPImporter.py", line 199, in __readMessagesFromFile
    packetReader.loop(nbPackets, self.__packetHandler)
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Import/PCAPImporter/PCAPImporter.py", line 248, in __packetHandler
    etherType) = self.__decodeLayer2(header, payload)
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Import/PCAPImporter/PCAPImporter.py", line 301, in __decodeLayer2
    layer2 = l2Decoder.decode(payload)
  File "/usr/local/lib/python3.4/dist-packages/Netzob-1.0.2-py3.4-linux-x86_64.egg/netzob/Import/PCAPImporter/ImpactDecoder.py", line 68, in decode
    elif e.get_ether_type() == ImpactPacket.ARP.ethertype:
AttributeError: 'module' object has no attribute 'ARP'

```
My bpfFilter:
`not (arp or host 192.168.56.255 or host 216.58.210.174 or host 212.106.221.82 or host 212.106.221.81 or host 212.106.221.76 or host 8.248.185.254 or host 216.58.210.164 or host 216.58.210.163 or host 8.8.8.8)`

In few pcaps file, the program works properly.

Thanks in advance!

**Comment by Sygus** [comment]
should work on version 2.0.0 as we now use again Impacket

**Comment by cybee42** [comment]
I have to use version 1.0.2, since I want to use [NetPlier](https://github.com/netplier-tool/NetPlier). NetPlier requires Netzob 1.0.2.
Now I run into a similar (the same?) problem:

`AttributeError: module 'netzob.Import.PCAPImporter.ImpactPacket' has no attribute 'ARP' `

Is there a fix for 1.0.2 as well?
